### ISSUE TITLE
Invalid API Key Provided

### ISSUE THREAD

**Issue by peterpme** [clearbit/clearbit-node#26]
Hey,

Awesome library!

For whatever reason, access has stopped working for me. I'm passing in a valid API key and I've tried both methods of instantiating the library.

The API key works because I tried CURL.

Any help would be appreciated!

Thanks,
Peter

**Comment by maccman** [comment]
Hi @peterpme can you contact support@clearbit.com

**Comment by peterpme** [comment]
Hey @maccman, thanks for your reply!

Are you saying I have to contact support to take care of issues for this clearbit api?

**Comment by davidlumley** [comment]
Hey @peterpme if could email us with the relevant details that would be great! It'll let us figure out if there's a problem with your account, or with this node package itself.

Thanks!
